export const data = [
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "1",
    Rank: "SI",
    Name: "KARAN SINGH",
    "Belt No.": "D-3398",
    "PIS No.": "28860554",
    "Mobile No.": "9999363646",
    "Present posting in District": "PS Lodhi Colony",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "1",
    Rank: "ASI",
    Name: "JAI RAM MEENA",
    "Belt No.": "447/SD",
    "PIS No.": "28010538",
    "Mobile No.": "9013310037",
    "Present posting in District": "PS Lodhi Colony",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "1",
    Rank: "CT",
    Name: "AMIT KUMAR",
    "Belt No.": "864/SD",
    "PIS No.": "28181349",
    "Mobile No.": "9953775150",
    "Present posting in District": "PS Lodhi Colony",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "1",
    Rank: "CT",
    Name: "RAJESH KUMAR",
    "Belt No.": "2454/SD",
    "PIS No.": "28160957",
    "Mobile No.": "9928542424",
    "Present posting in District": "PS Lodhi Colony",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "2",
    Rank: "SI",
    Name: "PREM SINGH",
    "Belt No.": "234/SD",
    "PIS No.": "28883149",
    "Mobile No.": "8587891080",
    "Present posting in District": "PS K M Pur",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "2",
    Rank: "HC",
    Name: "BHUDEV SHRMA",
    "Belt No.": "1565/SD",
    "PIS No.": "28093268",
    "Mobile No.": "9968463113",
    "Present posting in District": "PS K M Pur",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "2",
    Rank: "CT",
    Name: "SOMDUTT",
    "Belt No.": "3421/SD",
    "PIS No.": "28122443",
    "Mobile No.": "9560985334",
    "Present posting in District": "PS K M Pur",
  },
  {
    "AC No.": "42",
    "AC Name": "Kasturba Nagar",
    "Police District": "South",
    "Total Strength": "8",
    "Election District": "South East",
    "No. of Team": "2",
    Rank: "CT",
    Name: "PAWAN YADAV",
    "Belt No.": "1767/SD",
    "PIS No.": "28060975",
    "Mobile No.": "9968375427",
    "Present posting in District": "PS K M Pur",
  },

  {
    "AC No.": "43",
    "AC Name": "Malviya Nagar",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "HC",
    Name: "SHIV RAM",
    "Belt No.": "1335/SD",
    "PIS No.": "28093331",
    "Mobile No.": "9717338079",
    "Present posting in District": "P S CR PARK",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "43",
    "AC Name": "Malviya Nagar",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "ASI",
    Name: "Ramkishan",
    "Belt No.": "2548/SD",
    "PIS No.": "28961423",
    "Mobile No.": "9811483862",
    "Present posting in District": "P S Malviya Nagar",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "43",
    "AC Name": "Malviya Nagar",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "CT",
    Name: "Sunil",
    "Belt No.": "1119/SD",
    "PIS No.": "28183361",
    "Mobile No.": "7836003603",
    "Present posting in District": "P S Malviya Nagar",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "43",
    "AC Name": "Malviya Nagar",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "CT",
    Name: "Shersingh",
    "Belt No.": "3386/SD",
    "PIS No.": "28186391",
    "Mobile No.": "7088882687",
    "Present posting in District": "P S Malviya Nagar",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "45",
    "AC Name": "Mehrauli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "SI",
    Name: "DINESH KUMAR",
    "Belt No.": "1042/SD",
    "PIS No.": "28862879",
    "Mobile No.": "9958283780",
    "Present posting in District": "P S Mehrauli",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "45",
    "AC Name": "Mehrauli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "HC",
    Name: "MAHESH KUMAR",
    "Belt No.": "3191/SD",
    "PIS No.": "28105712",
    "Mobile No.": "8920897023",
    "Present posting in District": "P S Mehrauli",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "45",
    "AC Name": "Mehrauli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "CT",
    Name: "RINKU",
    "Belt No.": "3270/SD",
    "PIS No.": "28185919",
    "Mobile No.": "9636434006",
    "Present posting in District": "P S Mehrauli",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "45",
    "AC Name": "Mehrauli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "CT",
    Name: "ASHUTOSH",
    "Belt No.": "3211/SD",
    "PIS No.": "28183928",
    "Mobile No.": "8053859581",
    "Present posting in District": "P S Mehrauli",
    "Total Strength": "4",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "ASI",
    Name: "MAHESH KUMAR",
    "Belt No.": "1054/SD",
    "PIS No.": "28982177",
    "Mobile No.": "9953800717",
    "Present posting in District": "P S Maidan Garhi",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "HC",
    Name: "SHRI RAM KAJLA",
    "Belt No.": "3061/SD",
    "PIS No.": "28103602",
    "Mobile No.": "9968854476",
    "Present posting in District": "P S Maidan Garhi",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "CT.",
    Name: "DEVI SINGH",
    "Belt No.": "1731/SD",
    "PIS No.": "28109364",
    "Mobile No.": "8178842954",
    "Present posting in District": "P S Maidan Garhi",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "CT.",
    Name: "MAHIPAL",
    "Belt No.": "3068/SD",
    "PIS No.": "28102218",
    "Mobile No.": "9599169548",
    "Present posting in District": "P S Maidan Garhi",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "SI",
    Name: "Devender Singh",
    "Belt No.": "D-1317",
    "PIS No.": "16210142",
    "Mobile No.": "8744057787",
    "Present posting in District": "P S Fatehpur Beri",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "ASI",
    Name: "Jagroop Singh",
    "Belt No.": "262/SD",
    "PIS No.": "28892696",
    "Mobile No.": "9810964637",
    "Present posting in District": "P S Fatehpur Beri",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "HC",
    Name: "Manjeet",
    "Belt No.": "1698/SD",
    "PIS No.": "28102953",
    "Mobile No.": "9013466883",
    "Present posting in District": "P S Fatehpur Beri",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "46",
    "AC Name": "Chhatarpur",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "Ct.",
    Name: "Ashok Kumar",
    "Belt No.": "1131/SD",
    "PIS No.": "28121774",
    "Mobile No.": "9887708590",
    "Present posting in District": "P S Fatehpur Beri",
    "Total Strength": "8",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "ASI",
    Name: "Manhor lal",
    "Belt No.": "895/SD",
    "PIS No.": "28930563",
    "Mobile No.": "9868706496",
    "Present posting in District": "P S Tigri",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "HC",
    Name: "Brijesh",
    "Belt No.": "1035/SD",
    "PIS No.": "28110179",
    "Mobile No.": "9654967684",
    "Present posting in District": "P S Tigri",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "HC",
    Name: "SUNIL",
    "Belt No.": "1414/SD",
    "PIS No.": "28080868",
    "Mobile No.": "9711851623",
    "Present posting in District": "P S CR PARK",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",

    "No. of Team": "1",
    Rank: "Ct",
    Name: "Mahesh",
    "Belt No.": "1323/Sd",
    "PIS No.": "28122200",
    "Mobile No.": "8307040098",
    "Present posting in District": "P S Tigri",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "ASI",
    Name: "Rajneesh",
    "Belt No.": "154SD",
    "PIS No.": "28990096",
    "Mobile No.": "9953493338",
    "Present posting in District": "P S Neb Sarai",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "HC",
    Name: "Dinesh",
    "Belt No.": "1728/SD",
    "PIS No.": "28081099",
    "Mobile No.": "9999732878",
    "Present posting in District": "P S Neb Sarai",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "HC",
    Name: "Rajpal",
    "Belt No.": "3351/SD",
    "PIS No.": "29100683",
    "Mobile No.": "9717101186",
    "Present posting in District": "P S Neb Sarai",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "Ct",
    Name: "Manjeet",
    "Belt No.": "3116/Sd",
    "PIS No.": "28122059",
    "Mobile No.": "9991657253",
    "Present posting in District": "P S Neb Sarai",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "SI",
    Name: "BACHURAM",
    "Belt No.": "5603-D",
    "PIS No.": "28901318",
    "Mobile No.": "9958650911",
    "Present posting in District": "P S Saket",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "ASI",
    Name: "AJIT",
    "Belt No.": "511/SD",
    "PIS No.": "28105043",
    "Mobile No.": "8860136428",
    "Present posting in District": "P S Saket",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "CT",
    Name: "SAWAN",
    "Belt No.": "3049/SD",
    "PIS No.": "28182015",
    "Mobile No.": "9306011547",
    "Present posting in District": "P S Saket",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "47",
    "AC Name": "Deoli",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "CT",
    Name: "ARUN",
    "Belt No.": "1183/SD",
    "PIS No.": "28104811",
    "Mobile No.": "9999655086",
    "Present posting in District": "P S Saket",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "SI",
    Name: "DAL CHAND",
    "Belt No.": "361/SD",
    "PIS No.": "28877018",
    "Mobile No.": "9999729979",
    "Present posting in District": "P S Ambedkar Nagar",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "ASI",
    Name: "AJAY",
    "Belt No.": "115/SD",
    "PIS No.": "29920009",
    "Mobile No.": "9958287857",
    "Present posting in District": "P S Ambedkar Nagar",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "HC",
    Name: "MUKESH",
    "Belt No.": "735/SD",
    "PIS No.": "28103619",
    "Mobile No.": "9310755596",
    "Present posting in District": "P S Ambedkar Nagar",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "HC",
    Name: "SUNIL",
    "Belt No.": "1941/SD",
    "PIS No.": "28094285",
    "Mobile No.": "9540505030",
    "Present posting in District": "P S Ambedkar Nagar",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "SI",
    Name: "HARPHOOL",
    "Belt No.": "5561-D",
    "PIS No.": "28900807",
    "Mobile No.": "7339993267",
    "Present posting in District": "P S C R Park",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "ASI",
    Name: "CHATER SAIN",
    "Belt No.": "2949/SD",
    "PIS No.": "28880607",
    "Mobile No.": "9953686077",
    "Present posting in District": "P S C R Park",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "HC",
    Name: "PREETAM",
    "Belt No.": "1397/SD",
    "PIS No.": "28011052",
    "Mobile No.": "9999381864",
    "Present posting in District": "P S C R Park",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "CT",
    Name: "RAJESH",
    "Belt No.": "1751/SD",
    "PIS No.": "28120818",
    "Mobile No.": "8168857968",
    "Present posting in District": "P S C R Park",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "SI",
    Name: "Sukhlal",
    "Belt No.": "1889-D",
    "PIS No.": "28941183",
    "Mobile No.": "9953432865",
    "Present posting in District": "P S Hauz Khas",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "HC",
    Name: "Jitender",
    "Belt No.": "1855/SD",
    "PIS No.": "29102081",
    "Mobile No.": "8750807878",
    "Present posting in District": "P S Hauz Khas",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "CT",
    Name: "Sharwan",
    "Belt No.": "1642/SD",
    "PIS No.": "28122270",
    "Mobile No.": "9015293028",
    "Present posting in District": "P S Hauz Khas",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "48",
    "AC Name": "Ambedkar Nagar",
    "Police District": "South",
    "No. of Team": "3",
    Rank: "CT",
    Name: "Sanjeev",
    "Belt No.": "3242/SD",
    "PIS No.": "28186506",
    "Mobile No.": "8218750818",
    "Present posting in District": "P S Hauz Khas",
    "Total Strength": "12",
    "Election District": "South",
  },
  {
    "AC No.": "49",
    "AC Name": "Sangam Vihar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "ASI",
    Name: "BHAJAN LAL",
    "Belt No.": "1101/SD",
    "PIS No.": "28030371",
    "Mobile No.": "9968011148",
    "Present posting in District": "PS Sangam Vihar",
    "Total Strength": "4",
    "Election District": "South East",
  },
  {
    "AC No.": "49",
    "AC Name": "Sangam Vihar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "HC",
    Name: "JITENDER",
    "Belt No.": "1935/SD",
    "PIS No.": "29101214",
    "Mobile No.": "8920053404",
    "Present posting in District": "PS Sangam Vihar",
    "Total Strength": "4",
    "Election District": "South East",
  },
  {
    "AC No.": "49",
    "AC Name": "Sangam Vihar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "HC",
    Name: "BACCHOO SINGH",
    "Belt No.": "3060/SD",
    "PIS No.": "28061744",
    "Mobile No.": "9810684562",
    "Present posting in District": "PS Sangam Vihar",
    "Total Strength": "4",
    "Election District": "South East",
  },
  {
    "AC No.": "49",
    "AC Name": "Sangam Vihar",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "HC",
    Name: "CHARAN SINGH",
    "Belt No.": "1932/W",
    "PIS No.": "28105787",
    "Mobile No.": "7982916088",
    "Present posting in District": "PS Sangam Vihar",
    "Total Strength": "4",
    "Election District": "South East",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "ASI",
    Name: "RAM BABU",
    "Belt No.": "1184/SD",
    "PIS No.": "28890049",
    "Mobile No.": "9999366904",
    "Present posting in District": "P S Greater Kailash",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "ASI",
    Name: "MAHESH",
    "Belt No.": "4526/SD",
    "PIS No.": "28881697",
    "Mobile No.": "9968830834",
    "Present posting in District": "P S Greater Kailash",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "ASI",
    Name: "SATENDRA",
    "Belt No.": "1601/SD",
    "PIS No.": "28883195",
    "Mobile No.": "8920023079",
    "Present posting in District": "P S Greater Kailash",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "1",
    Rank: "HC",
    Name: "VARUN",
    "Belt No.": "1377/SD",
    "PIS No.": "28092082",
    "Mobile No.": "9555793406",
    "Present posting in District": "P S Greater Kailash",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "ASI",
    Name: "Chander Pal",
    "Belt No.": "1830/SD",
    "PIS No.": "28961439",
    "Mobile No.": "9971945078",
    "Present posting in District": "P S Defence Colony",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "ASI",
    Name: "Omprakash",
    "Belt No.": "902/SD",
    "PIS No.": "28981190",
    "Mobile No.": "7678410919",
    "Present posting in District": "P S Defence Colony",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "HC",
    Name: "Saurabh Kumar",
    "Belt No.": "1843/SD",
    "PIS No.": "28100861",
    "Mobile No.": "8586014233",
    "Present posting in District": "P S Defence Colony",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
  {
    "AC No.": "50",
    "AC Name": "Greater Kailash",
    "Police District": "South",
    "No. of Team": "2",
    Rank: "HC",
    Name: "Gajender",
    "Belt No.": "261/SD",
    "PIS No.": "28100126",
    "Mobile No.": "9873029404",
    "Present posting in District": "P S Defence Colony",
    "Total Strength": "8",
    "Election District": "New Delhi",
  },
];
