export const rankwiseData = [
  {
    "SL. NO.": 1.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL, OPP ARYA SAMAJ MANDIR,DARAGG, MEHRAULI",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "98, 99, 100, 101, 102, 103, 104, 105, 106, 107",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 2.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "ST.JOHNS SCHOOL WARD NO.1,MEHRAULI",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "108, 109",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 3.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "GOVT.BOYS SR.SECONDARY SCHOOL,NO.2,MAIN BAZAR,MEHRAULI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "110, 111, 112, 113, 114, 115, 116",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 4.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "MCD PRIMARY PRATIBHA SCHOOL (GIRL)4/323 MEHRAULI",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "128, 129, 130, 131",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 5.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "MCD PRIMARY PRATIBHA CO-ED KOTHI KALE KHAN,MEHRAULI",
    "TOTAL NUMBER OF PS ON LOCATION": 11.0,
    "PS NUMBERS": "117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 5.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 10.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 26,
  },
  {
    "SL. NO.": 6.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "RAMANAJUN SARVODAYA KAMYA VIDYALAY, MEHRAULI ",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "132, 133, 134, 135, 136, 137, 138, 139, 140, 141",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 7.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "GOVT BOYS SR.SECONDARY SCHOOL NO.3 MEHRAULI",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "142, 143, 144, 145, 146, 147, 148, 149",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 8.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "NIGAM PRATIBHA VIDYALAY ,SAIDU LAJAB",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "1, 2, 3, 4, 5, 10, 11,",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 9.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME":
      "O/O EX.ENG.CIVIL DIV.V DEPT OF IRRIAGTION FLOOD CONTROL PARYAVARAN COMPLEX",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "6, 7, 8, 9",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 10.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "GOVT.GIRLS SR.SECONDARY SCHOOL,CHATTARPUR",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "43, 44, 45, 46, 47, 48, 49, 50, 51, 60",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 11.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "NIGAM PRATIBHA VIDYALAY ,CHATTARPUR MANDIR",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "52, 53, 54, 55, 56, 57, 58, 59,  76",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 12.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "ACHARYA TULSI SARVODAYA VIDYALYA,CHATTARPUR",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "61, 62, 63, 64, 65, 66, 67, 68, 69, 70",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 13.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD PRIMARY SCHOOL CHATTARPUR MANDIR",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "71, 72, 73, 74, 75,",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 14.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD PRIMARY SCHOOL,SATBARI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "82, 83, 84",
    "POLICE STATION": "MEHRAULI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 15.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "GOVT CO-ED SEC SCHOOL NEB SARAI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "12, 13, 14, 15, 16, 17, 18",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "CRITICAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 16.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "IGNOU COMPLEX MAIDAN GARHI",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "25, 26",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 17.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "NIGAM PRATIBHA VIDJHYALYA NEB SARAI",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "19, 20, 21, 22, 23, 24",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "CRITICAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 18.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "DURGA PIBLIC SCHOO; A 30 DURGA VIHAR DEVLI VILLAGE DURGA VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "140, 141, 142",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 19.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "J.M PUBLIC SCHOOL A-365 DURGA VIHAR DEVLI VILLAGE DURGA VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "143, 144 ",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 20.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "MCD PRIMARY SCHOOL NO.1 DEVLI VILLAGE",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "126, 127, 128, 129, 130, 131",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "CRITICAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 21.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "SDMC PRIOMARY SCHHOL NO.2 DEVLI VILLAGE DEVLI",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "132, 133, 134, 135, 136, 145",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "CRITICAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 22.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "CH.SAHIB SINGH MEMORIAL PUBLIC SCHOOL .L-1/198 SANAGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "202, 203, 204, 205, 206, 207",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 23.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "MC PRIMARY SCHOOL BLOCK-L,SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "180, 181, 182, 186, 187, 188, 189",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 24.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "MNDP PUBLIC SCHOOL L-1ST/33 (NEAR ASTHAL MANDI) SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "192, 193, 194",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 25.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "MODERN SAVITIR PUBLIC SCHOOL L-1/12 (NEAR ASTHAL MANDI) SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "156, 183, 184, 185",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 26.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "SHIV SHAKTI PUBLIC SCHOOL ,L-1 (NEAR ASTHAL MANDI) SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "195, 196, 197, 198, 199, 200, 201",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 27.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "SINGHAL PUBLIC SCHOOL L-I/2073 (NEAR ASTHAL MANDI) SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "208, 209, 210",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 28.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "WHITE ROSE PUBLIC SCHOOL,L-1ST/1657,GALI NO.30 SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "157, 158, 190, 191",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 29.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "HAKIKAT RAI SARVODYA VIDHYALA,SHIV PARK KANPUR,ND",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "121, 122, 123, 124, 125, 126, 127, 128, 129, 130",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 30.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "MCD PRIMARY SCHOOL (GIRLS) KHANPUR VILLAGE ",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "105, 106, 107, 109",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 31.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "GOVT.BOYS SEC,SCHOOL NO.1 SCHOOL ROAD KHANPUR VILLAGE NEAR DTC DEPOT",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "85, 97, 98,99, 100, 101, 102, 103, 108",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 32.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary School, New Manglapuri, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "77, 78",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 33.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary Co-ED School, Chandan Hulla",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "85, 86, 87, 88",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 34.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary School (Girls), Fatehpur Beri, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "90, 91, 92, 93, 94, 95",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 35.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Pratibha (Boys) School, Fatehpur Beri, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "96, 97, 98, 99, 100, 101",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 36.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Govt. Sarvodaya Bal Vidyalaya, Fatehpur Beri, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "102, 103, 104, 105, 106",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 37.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME":
      "MCD PRIMARY CO-ED (ADARSH) VIDHYALAY, DERA VILLAGE, NEW DELHI.",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "172, 173, 174, 175",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 38.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary Asarsh Vidyala, Sultanpur, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "116, 117, 118, 119, 120, 121, 122, 123, 124",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 39.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary School, Jonapur, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "107, 108, 109, 110, 111, 112, 113",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 40.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary Co-Ed School, Gadaipur, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "114, 115",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 41.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Sarvodya Kanya Vidyalaya, Aya Nagar, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "134, 135, 142, 143, 153, 154, 155",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 42.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Govt. Boys Sr. Sec. School, Aya Nagar, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "138, 139, 140, 141",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 43.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Pratibha Co-Ed Vidyalaya Aya Nagar, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "136, 146, 147, 148, 149, 150, 151, 152, 156",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 44.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME":
      "St. Paul\u2019s Public School, H-Block, Phase-VI, Aya Nagar Colony, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 11.0,
    "PS NUMBERS": "137, 144, 145, 157, 158, 159, 160, 161, 162, 163, 164",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 5.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 10.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 26,
  },
  {
    "SL. NO.": 45.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Sarvodaya Kanya Vidyalaya, Mandi Village, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "165, 166, 167, 168",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 46.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Govt. Boys Sr. Sec. School Mandi, New Delhi",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "169, 170, 171",
    "POLICE STATION": "Fatehpur Beri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 47.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-2 NEAR BLOCK-9 & 9 DAKSHIN PURI EXTN",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "1, 2, 17, 21, 22, 23, 24, 25",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 48.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-4, NEAR BLOCK-4, DAKSHIN PURI EXTN.",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "10, 3, 35, 4, 5, 6, 7, 8, 9",
    "POLICE STATION": "Ambedkar Nagar",
    "CRITICAL/ NORMAL": "Critical",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 49.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-1 OPP POLICE STATION CR PARK DR AMBDEKAR NAGAR DAKSHIN PURI EXTN",
    "TOTAL NUMBER OF PS ON LOCATION": 11.0,
    "PS NUMBERS": "11, 12, 13, 14 ,15, 16, 26, 27 ,28 ,29 ,30",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 5.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 10.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 26,
  },
  {
    "SL. NO.": 50.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL MADANGIRI VILLAGE NEAR POLICE POST MADANGIR VILLAGE",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "18, 19, 20",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 51.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "SDMC PRIMARY SCHOOL NO-5 DAKSHINPURI EXTN NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "31, 32",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 52.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "GOVT.GIRLS SEC SCHOOL NO-2 SEC-5 DR AMBDEKAR NAGAR DAKSHIN PURI EXTN (NEAR KALI BUILDING )DDA FLATS",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "33, 34, 46, 47, 48, 49, 50,51, 52, 53, ",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 53.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "GOVT SARVODAYA VIDHYALA DR AMBEDKAR NAGAR SECTOR-5 DAKSHINPURI EXTN",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "36, 37, 38, 39, 40, 41",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 54.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "GOVT GIRLS SECONDAY SCHOO; NO.1 SECTOR 5,DR AMBEDKAR NAGAR DAKSHINPURI NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "42, 43, 44, 45, 54, 55",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 55.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "THE CAMBRIDGE INTERNATIONAL SCHOOL",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "117, 118, 119, 120, 131, 132, 133, 134, 135",
    "POLICE STATION": "NEB SARAI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 56.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "YOGI ARVIND SARVODYA VIDYALAYA SECTOR-4 DR AMBEDKAR NAGAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "24, 25, 26, 27, 28 ,29, 30, 31, 32",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 57.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-1 (BOYS) DR.AMBEDKAR NAGAR SECTOR-4 NEAR CENTRAL MARKAT MADANGIR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "33, 34, 35, 36, 37 ,38, 39, 41",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 58.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD PRIMARY CO-ED SCHOOL NO-1 DR.AMBEDKAR NAGAR SECTOR-5 DAKSHIN PURI BLOCK-D NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "42, 43, 44, 45, 46, 47, 84",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 59.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-3 NEAR BLOCK-K DAKSHINPURI DR AMBEDKAR NAAGR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "48, 49, 50, 51",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 60.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "GOVT.SR.SEC.GIRLS/BOYS SCHOOL (SHAHEED ANUSYA PRASAD(OPP.BLOCK-J SECTOR-5 DAKLSHINPURI NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "52, 53, 54, 55, 56, 57, 58, 59 ,60 ,61",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 61.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-2 SECTOR-3 DR.AMBEDKAR NAGAR NEAR CENTRAL MKT",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "62, 63, 64, 65, 66",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 62.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD CO-ED SCHOOL NO.3 DR AMBEDKAR NAGAR SECTOR-4 MADANGIRI (PHASE-2) NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "67, 68, 69, 70 ,71, 72, 81",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 63.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "GOVT.GIRLS SR.SEC SCHOOL NO-2 (PILI BUILDING) DR AMBEDKAR NAGAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "73, 74,75,76,77",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 64.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "SARVODYA BAL VIDHYALAY (2ND  SHIFT) BACK SIDE OF CENTER MARKET,SECTOR-4 ,DR.AMBEDKAR NAGAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "78, 79, 80, 82, 83",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 65.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL NO-2 BLOCK-F & G,A-WING LEFT SIDE.SECTOR-5,DAKSHINPURI,DR AMBEDKAR NAGAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "87, 88, 89, 90 ,91,92, 93,94,95,96",
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 66.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "MCD PRIMARY SCHOOL RPS NEAR HARIJAN BASTI CAMP,M.B.ROAD KHANPUR",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": 86104,
    "POLICE STATION": "AMBEDKAR NAGAR ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 67.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      " ANAND VIDHYA BHARTI EDU-SOCIETY SCHOOL (PLAY GROUND), F-2 BLOCK, SANGAM VIHAR, NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "56, 57",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 68.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      " ANAND VIDHYA BHARTI EDU-SOCIETY SCHOOL (SCHOOL BUILDING), F-2 BLOCK, SANGAM VIHAR, NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "58, 59, 60",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 69.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      " GREEN ARAVALI PUBLIC SCHOOL,  I-BLOCK ,SANGAM VIHAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "99 TO 103 ",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 70.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME": " HAMDARD PUBLIC SCHOL, RATIYA MARG, SANGAM VIHAR ND",
    "TOTAL NUMBER OF PS ON LOCATION": 15.0,
    "PS NUMBERS": "65 TO 79",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 6.0,
    HC: 2.0,
    CT: 8.0,
    "W/CT": 2.0,
    DHG: 13.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 33,
  },
  {
    "SL. NO.": 71.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      " JEEVAN JYOTI PUBLIC SCHOOL, GALI NO.5, D-BLOCK, SANGAM VIHAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "43,44,45",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 72.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "KENDRIYA VIDHYALAYA SCHOOL (AFS), MB ROAD, HAMDARD NAGAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "35 TO 42",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 73.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      ",KSK ACADEMY, H-BLOCK, GALI NO.-17, RATIYA MARG, SANGAM VIHAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "143 TO 149",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 74.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "NEW SANGAM PUBLIC SCHOOL,K-1/30, K-BLOCK, SANGAM VIHAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "130 TO 133",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 75.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "NEW SATYAM PUBLIC SCHOOL, GALI NO.-6, E-BLOCK, SANGAM VIHAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "46 ,47, 48",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 76.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "NIGAM PRATIBHA KANYA VIDHYALAYA,F-2 BLOCK, SANGAM VIHAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "61 TO 64",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 77.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "SARVODYA KANYA VIDHYALAYA, J-BLOCK,S ANGAM VIHAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 13.0,
    "PS NUMBERS": "117 TO 129",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 6.0,
    HC: 2.0,
    CT: 5.0,
    "W/CT": 2.0,
    DHG: 11.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 28,
  },
  {
    "SL. NO.": 78.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "SIVAS PUBLIC SCHOOL, MANGAL BAZAR ROAD, F-1ST BLOCK, SANGAM VIHAR,NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "49 TO 55",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 79.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "SHRIOMNI SCHOOL K-19/11/994 K-BLOCK SANGAM VIHAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "134,135, 136",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 80.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "HOMLY IDEAL   PUBLIC SCHOOL, H-BLCK GALI NO.16, SANGAM VIHAR,ND",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "94 TO 98",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 81.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "SOUTH DELHI MODEL PUBLIC SCHOOL K, 1/174,K-BLOCK,GALI NO-18,SANGAM VIHAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "137 TO 142",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 82.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "VIJAY BHARTI PUBLIC SCHOOL, GALI NO.-16, H-BLOCK, SANGAM VIHAR,ND",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "89 TO 92",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 83.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME": "MCD PRIMARY SCHOOL , I BLOCK, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 13.0,
    "PS NUMBERS": "104 TO 116",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 6.0,
    HC: 2.0,
    CT: 5.0,
    "W/CT": 2.0,
    DHG: 11.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 28,
  },
  {
    "SL. NO.": 84.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME": "M.R.JAIN PUBLIC SCHOOL, H-BLOCK GALI NO-16, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 10.0,
    "PS NUMBERS": "80 TO 88 & 93",
    "POLICE STATION": "SANGAM VIHAR",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 2.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 9.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 23,
  },
  {
    "SL. NO.": 85.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "AMRITA PUBLIC SCHOOL K-II/474, SANGAM  VIHAR, NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "159, 160, 161, 162,\n163, 164, 165",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 86.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "BACHAN       PRASAD SKV SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "146,147,148,149,15\n0,151,152,\n153",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "Normal",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 87.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "BAL NIKETAN PUBLIC SCHOOL BLOCK A 51 SANGAM  VIHAR, NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "92,93,94,95,96,106,\n107",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "Normal",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 88.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "CHILDREN TINU PUBLIC SCHOOL B- BLOCK SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "115,116,117,118,11\n9, ",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 89.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "COMMUNITY HALL (BLOCK A- JJ COLONY TIGRI",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "74, 75, 76, 77",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 90.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "GOVT. GIRLS/BOYS SENIOR SECONDARY SCHOOL C- BLOCK SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "120, 121,122,123,124,12\n5",
    "POLICE STATION": "Tigri",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 91.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "HARI VIDHYA BHAWAN K-II/600 SANGAM VIHAR NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "166,167,168,169,17\n0",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 92.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "HIMGIRI         PUBLIC SCHOOL    B-1265/3, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "72, 73",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 93.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "IG  MEMORIAL PUBLIC SCHOOL L- 725, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "154,155,176,177,17\n8,179",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 94.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "LVS PUBLIC SCHOOL B-19,  SANGAM VIHAR, NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "100, 101",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 95.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "MCD PRIMARY SCHOOL NO.1 TIGRI JJ COLONY TIGRI",
    "TOTAL NUMBER OF PS ON LOCATION": 11.0,
    "PS NUMBERS": "62, 63, 64, 65, 78,79, 84, 85, 86, 87,88",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 5.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 10.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 26,
  },
  {
    "SL. NO.": 96.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "MCD PRIMARY SCHOOL NO.2 TIGRI JJ COLONY TIGRI",
    "TOTAL NUMBER OF PS ON LOCATION": 11.0,
    "PS NUMBERS": "66, 67, 68, 69, 70,71, 80, 81, 89, 90, 91",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 1.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 5.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 10.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 26,
  },
  {
    "SL. NO.": 97.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "NEW JAI BHARTI PUBLIC SCHOOL B- BLOCK SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "108, 109",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 98.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "NEW SURYA PUBLIC SCHOOL B- 110, NEAR PANDEY KI KOTHI, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "97, 98, 99",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 99.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "SAI NATH PUBLIC SCHOOL C-8 & C-9, TIGRI EXTN, NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "56, 57, 58, 59, 60",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 100.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "SATYA SAI PUBLIC SCHOOL 682/1 NAI BASTI              DEOLI\nVILLAGE,   NEW DELHI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "137, 138, 139",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 101.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "SS PUBLIC SCHOOL B-545, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "110,111,112,113,11\n4",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 102.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "THE  SANGAM PUBLIC SCHOOL L- 1222/4, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "171,172,173,\n174,175",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 103.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME": "TIGRI MAHILA VIKAS SANGH OPP DDA FLATS JJ CAMP TIGRI",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "61, 82, 83",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 104.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "DEOLI-47",
    "LOCATION NAME":
      "TINU              PUBLIC\nSCHOOL        B-1189, SANGAM VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "102,103,104, 105",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 105.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "SANGAM VIHAR-49",
    "LOCATION NAME":
      "SCHOOL  OF PHARMACEUTICAL EDUCTION AND RESEARCH (SPER). JAMIA HAMDARD NAGAR",
    "TOTAL NUMBER OF PS ON LOCATION": 1.0,
    "PS NUMBERS": 1,
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 0.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 1.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 4,
  },
  {
    "SL. NO.": 106.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "SONA             MODEL\nPUBLIC        SCHOOL KHANPUR EXTENSION       MAIN MARKET KHANPUR",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "110,111,112,113,11\n4,115,116",
    "POLICE STATION": "TIGRI",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 107.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "MCD PRATIBHA CO-ED, SECTOR-7, PUSHP VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "1,2,11,12,13,14,15,",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 108.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "SARVODAYA KANYA SECONDARY SCHOOL, SECTOR-1, PUSHP VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "3,4,5,6,7,8,9,10",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 109.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "MCD PRIMARY SCHOOL, SECTOR-5, PUSHP VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "16,17,18",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 110.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME": "KENDRIYA VIDYALAYA SECTOR-3, PUSHP VIHAR",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "19,20,21,22,23, 40",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 111.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "AMBEDKAR NAGAR-48",
    "LOCATION NAME":
      "Delhi Pharmaceutical Science and Research University (DIPSAR)",
    "TOTAL NUMBER OF PS ON LOCATION": 5.0,
    "PS NUMBERS": "136,137, 138,139,140",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 1.0,
    DHG: 5.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 12,
  },
  {
    "SL. NO.": 112.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME":
      "SDMC ADARSH KANYA VIDYALAYA, LADO SARAI VILLAGE, LADO SARAI, NEW DELHI-110030",
    "TOTAL NUMBER OF PS ON LOCATION": 9.0,
    "PS NUMBERS": "150, 151, 152, 153, 154, 155, 156, 157, 158",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 8.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 21,
  },
  {
    "SL. NO.": 113.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "SDMC PRIMARY SCHOOL (BOYS), LADO SARAI, NEW DELHI-110030",
    "TOTAL NUMBER OF PS ON LOCATION": 7.0,
    "PS NUMBERS": "159, 160, 161, 162, 163, 164, 165, ",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 5.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 17,
  },
  {
    "SL. NO.": 114.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "GYAN BHARTI PUBLIC SCHOOL, SAKET, NEW DELHI-110017",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "166, 169, 170, 171,",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 115.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME":
      "RED ROSES PUBLIC SCHOOL, D-BLOCK, SAKET, NEW DELHI-110017",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "167, 168, 179",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 116.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME":
      "NEW GREEN FIELD SCHOOL, L-BLOCK , SAKET, NEW DELHI-110017",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "172, 173",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 117.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME": "APPEE JAY SCHOOL, BLOCK-J, SAKET, NEW DELHI-110017",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "174,175,",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 118.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "MEHRAULI-45",
    "LOCATION NAME":
      "SDMC PRIMARY MODEL SCHOOL, G-BLOCK, SAKET, NEW DELHI-110017",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "176,177, 178",
    "POLICE STATION": "Saket ",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 119.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Co-ed Primary School Maidan Garhi",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "27, 28, 29, 30, 31, 32",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 120.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary Co-ed School, Rajpur Khurd Extension",
    "TOTAL NUMBER OF PS ON LOCATION": 6.0,
    "PS NUMBERS": "33, 34, 35, 36, 37, 38",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "CRITICAL ",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 4.0,
    HC: 2.0,
    CT: 2.0,
    "W/CT": 2.0,
    DHG: 6.0,
    CAPF: "1/2 Sec. + 02 HC   ",
    "TOTAL (ACP TO DHG": 16,
  },
  {
    "SL. NO.": 121.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Saptarshi Public School Rajpur Khurd 04Extension",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "39, 40",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 122.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Community Center, Near Shiv Gorakh Mandir Rajpur Khurd",
    "TOTAL NUMBER OF PS ON LOCATION": 2.0,
    "PS NUMBERS": "41, 42",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 2.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 6,
  },
  {
    "SL. NO.": 123.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "CSKM Public School Satbari",
    "TOTAL NUMBER OF PS ON LOCATION": 4.0,
    "PS NUMBERS": "79, 80, 81, 89",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 2.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 4.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 9,
  },
  {
    "SL. NO.": 124.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary Co-ed School Bhatti Village",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "176, 177, 178",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
  {
    "SL. NO.": 125.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "Govt. Co-ed Sr.  Sec. School, Sanjay Colony Bhati Mines",
    "TOTAL NUMBER OF PS ON LOCATION": 8.0,
    "PS NUMBERS": "179, 180, 181, 182, 183, 184, 185, 186",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 1.0,
    "U/S": 4.0,
    HC: 3.0,
    CT: 3.0,
    "W/CT": 2.0,
    DHG: 7.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 20,
  },
  {
    "SL. NO.": 126.0,
    "PC NAME & NO.": "SOUTH DELHI-07",
    "AC NAME & AC NO.": "CHATTARPUR-46",
    "LOCATION NAME": "MCD Primary School Bhatti Mines",
    "TOTAL NUMBER OF PS ON LOCATION": 3.0,
    "PS NUMBERS": "187, 188, 189",
    "POLICE STATION": "Maidan Garhi",
    "CRITICAL/ NORMAL": "NORMAL",
    ACP: 0.0,
    "INSPR.": 0.0,
    "U/S": 1.0,
    HC: 1.0,
    CT: 1.0,
    "W/CT": 1.0,
    DHG: 3.0,
    CAPF: 0,
    "TOTAL (ACP TO DHG": 7,
  },
];
